services:
  - type: web
    name: calanco-api
    env: node
    plan: free
    buildCommand: node --no-warnings ./node_modules/@nestjs/cli/bin/nest.js build
    startCommand: npm run start:prod
    rootDir: .
    envVars:
      - key: SUPABASE_URL
        fromDashboard: true
      - key: SUPABASE_KEY
        fromDashboard: true
      - key: WEATHER_API_KEY
        fromDashboard: true
